In [1236]:
import itertools
import re
import sympy as sp
import numpy as np
from scipy.optimize import minimize
from typing import *

In [1237]:
def get_expectation(nr_persons: int, nr_tickets: int) -> sp.core.add.Add:
    if nr_tickets > nr_persons:
        raise ValueError("Nr. persons should be less than nr. tickets.")
    if nr_tickets >= 100 or nr_persons >= 100:
        raise ValueError("Nr. person and nr. tickets should be less than 100.")

    _difference_ = nr_persons - nr_tickets

    ## Creating and ordering sympy variables in table ##
    variable_table = np.empty(shape=(nr_persons,nr_tickets),dtype=object)
    person_indexes = [i+1 for i in range(nr_persons)]
    for ticket in range(nr_tickets):
        for person in range(nr_persons):
            if ticket <= person:
                variable_table[person,ticket] = sp.Symbol("p"+str(person+1)+str(ticket+1))

    ## Calculating all combinations of letting n persons buy k tickets (k<n) ##
    combos = []
    for ticket_number in range(1,nr_tickets+1):
        combs = list(itertools.combinations(person_indexes,ticket_number))
        combos.append([list(comb) for comb in combs])
    combos = np.array(combos,dtype=object)

    ## Calculating expectation value ##
    __expectation = sp.sympify(0)
    for combinations in combos:
        for persons in combinations:
            nr_tickets = len(persons)
            person_nr, ticket_nr = 0, 0
            term, term_weight = sp.sympify(1), sp.sympify(0)
            while person_nr < nr_persons:
                if ticket_nr < nr_tickets:
                    person_buying = persons[ticket_nr]
                    if person_nr + 1 == person_buying:
                        term *= (1-variable_table[person_nr][ticket_nr])   # Buying
                        term_weight += variable_table[person_nr][ticket_nr]
                        ticket_nr += 1
                        if ticket_nr == nr_persons-_difference_:
                            break
                    else:
                        term *= variable_table[person_nr][ticket_nr]      # Not Buying
                else:
                    term *= variable_table[person_nr][ticket_nr]          # Not Buying
                person_nr += 1
            __expectation += term_weight*term
    return __expectation

def optimize_equations(symbols: List[sp.Symbol], equations: List[sp.Expr],
                       initial_guess: Union[List[float],np.ndarray[float]]) -> np.ndarray:
    """
    Given a list of symbols, a list of equations, and an initial guess, optimize the values of the symbols
    that minimize the sum of squares of the equations using the scipy.optimize.minimize function.
    Returns an array of optimized values of the symbols.

    Args:
        symbols: A list of sympy symbols to optimize.
        equations: A list of sympy expressions representing the equations to solve.
        initial_guess: A list of initial guesses for the values of the symbols.

    Returns:
        An array of optimized values of the symbols.

    Raises:
        ValueError: If the length of symbols and initial_guess does not match.
    """
    if len(symbols) != len(initial_guess):
        raise ValueError("Length of symbols and initial_guess must match")

    # Create a function that takes in the values of the symbols and returns the equation
    f = sp.lambdify(symbols, equations)

    # Define the optimization problem
    _bounds = [(0, 1) for _var in symbols]
    _problem = minimize(lambda x: np.sum(np.square(f(*x))), initial_guess, bounds=_bounds)

    # Print the optimized values
    for i in range(len(symbols)):
        print(f'{symbols[i]}: {np.round(_problem.x[i], 6)}')

    return _problem.x

# 2 tickets - 3 persons:
##### (Manually):

In [1238]:
p11, p21, p31 = sp.symbols("p11, p21, p31")
p22, p32      = sp.symbols("p22, p32")

vars = [p11, p21, p22, p31, p32]
# only 1 of 2 tickets bought amongst 3 persons
term1 = p11*(1-p11)*(1-(1-p22))*(1-(1-p32))
term2 = p21*(1-(1-p11))*(1-p21)*(1-(1-p32))
term3 = p31*(1-(1-p11))*(1-(1-p21))*(1-p31)
# 2 of 2 tickets bought amongst 3 persons
term4 = (p11+p22)*(1-p11)*(1-p22)
term5 = (p11+p32)*(1-p11)*(1-(1-p22))*(1-p32)
term6 = (p21+p32)*(1-(1-p11))*(1-p21)*(1-p32)
expectation = term1+term2+term3+term4+term5+term6

# Writing out diff equations to .txt file for easy Ctrl-C Ctrl-V
file = open("3persons2tickets.txt", "w")
for idx, var in enumerate(vars):
    __ = f"eq{idx+1}="+str(sp.diff(expectation,var))
    file.write(re.sub(r"\s+", "", __)+"\n\n")
file.close()

equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(3,2))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

p11: 0.554688
p21: 0.5
p22: 0.625
p31: 0.5
p32: 0.5

 == Corresponding to: == 
[[0.55469 0.     ]
 [0.5     0.625  ]
 [0.5     0.5    ]]


##### (Automatically):

In [1239]:
expectation = get_expectation(nr_persons=3,nr_tickets=2)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(3,2))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None]
 [p21 p22]
 [p31 p32]]
p11: 0.554688
p21: 0.5
p22: 0.625
p31: 0.5
p32: 0.5

 == Corresponding to: == 
[[0.55469 0.     ]
 [0.5     0.625  ]
 [0.5     0.5    ]]


# 2 tickets - 4 persons:

In [1240]:
p11, p21, p31, p41 = sp.symbols('p11, p21, p31, p41')
p22, p32, p42      = sp.symbols('p22, p32, p42')

vars = [p11, p21, p31, p41, p22, p32, p42]

# Only 1 of 3 tickets bought amongst 4 persons
term1 = p11*(1-p11)*(1-(1-p22))*(1-(1-p32))*(1-(1-p42))
term2 = p21*(1-(1-p11))*(1-p21)*(1-(1-p32))*(1-(1-p42))
term3 = p31*(1-(1-p11))*(1-(1-p21))*(1-p31)*(1-(1-p42))
term4 = p41*(1-(1-p11))*(1-(1-p21))*(1-(1-p31))*(1-p41)

# 2 of 2 tickets bought amongst 4 persons
term5 = (p11+p22)*(1-p11)*(1-p22)
term6 = (p11+p32)*(1-p11)*(1-(1-p22))*(1-p32)
term7 = (p11+p42)*(1-p11)*(1-(1-p22))*(1-(1-p32))*(1-p42)
term8 = (p21+p32)*(1-(1-p11))*(1-p21)*(1-p32)
term9 = (p21+p42)*(1-(1-p11))*(1-p21)*(1-(1-p32))*(1-p42)
term10 = (p31+p42)*(1-(1-p11))*(1-(1-p21))*(1-p31)*(1-p42)

# Expectation
expectation = term1 + term2 + term3 + term4 + \
              term5 + term6 + term7 + term8 + \
              term9 + term10

# Writing out diff equations to .txt file for easy Ctrl-C Ctrl-V
file = open("4persons2tickets.txt", "w")
for idx, var in enumerate(vars):
    __ = f"eq{idx+1}="+str(sp.diff(expectation,var))
    file.write(re.sub(r"\s+", "", __)+"\n\n")
file.close()

equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)
table = np.zeros(shape=(4,2))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

p11: 0.607422
p21: 0.554686
p31: 0.5
p41: 0.5
p22: 0.695312
p32: 0.625
p42: 0.5

 == Corresponding to: == 
[[0.60742 0.     ]
 [0.55469 0.69531]
 [0.5     0.625  ]
 [0.5     0.5    ]]


###### (Automatically):

In [1241]:
expectation = get_expectation(nr_persons=4,nr_tickets=2)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(4,2))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None]
 [p21 p22]
 [p31 p32]
 [p41 p42]]
p11: 0.607422
p21: 0.554686
p31: 0.5
p41: 0.5
p22: 0.695312
p32: 0.625
p42: 0.5

 == Corresponding to: == 
[[0.60742 0.     ]
 [0.55469 0.69531]
 [0.5     0.625  ]
 [0.5     0.5    ]]


# 3 Tickets - 4 persons:

In [1242]:
p11, p21, p31, p41 = sp.symbols('p11, p21, p31, p41')
p22, p32, p42      = sp.symbols('p22, p32, p42')
p33, p43           = sp.symbols('p33, p43')

vars = [p11, p21, p31, p41, p22, p32, p42, p33, p43]

# 1 of 3 tickets bought amongst 4 persons
term1 = p11*(1-p11)*(1-(1-p22))*(1-(1-p32))*(1-(1-p42))
term2 = p21*(1-(1-p11))*(1-p21)*(1-(1-p32))*(1-(1-p42))
term3 = p31*(1-(1-p11))*(1-(1-p21))*(1-p31)*(1-(1-p42))
term4 = p41*(1-(1-p11))*(1-(1-p21))*(1-(1-p31))*(1-p41)

# 2 of 3 tickets bought amongst 4 persons
term5 = (p11+p22)*(1-p11)*(1-p22)*(1-(1-p33))*(1-(1-p43))
term6 = (p11+p32)*(1-p11)*(1-(1-p22))*(1-p32)*(1-(1-p43))
term7 = (p11+p42)*(1-p11)*(1-(1-p22))*(1-(1-p32))*(1-p42)
term8 = (p21+p32)*(1-(1-p11))*(1-p21)*(1-p32)*(1-(1-p43))
term9 = (p21+p42)*(1-(1-p11))*(1-p21)*(1-(1-p32))*(1-p42)
term10 = (p31+p42)*(1-(1-p11))*(1-(1-p21))*(1-p31)*(1-p42)

# 3 of 3 tickets bought amongst 4 persons
term11 = (p11+p22+p33)*(1-p11)*(1-p22)*(1-p33)
term12 = (p11+p22+p43)*(1-p11)*(1-p22)*(1-(1-p33))*(1-p43)
term13 = (p11+p32+p43)*(1-p11)*(1-(1-p22))*(1-p32)*(1-p43)
term14 = (p21+p32+p43)*(1-(1-p11))*(1-p21)*(1-p32)*(1-p43)

# Expectation
expectation = term1 + term2 + term3 + term4 + \
              term5 + term6 + term7 + term8 + \
              term9 + term10 + term11 + term12 + \
              term13 + term14

# Writing out diff equations to .txt file for easy Ctrl-C Ctrl-V
file = open("4persons3tickets.txt", "w")
for idx, var in enumerate(vars):
    __ = f"eq{idx+1}="+str(sp.diff(expectation,var))
    file.write(re.sub(r"\s+", "", __)+"\n\n")
file.close()

equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)
table = np.zeros(shape=(4,3))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

p11: 0.525848
p21: 0.5
p31: 0.5
p41: 0.5
p22: 0.554691
p32: 0.5
p42: 0.5
p33: 0.625006
p43: 0.5

 == Corresponding to: == 
[[0.52585 0.      0.     ]
 [0.5     0.55469 0.     ]
 [0.5     0.5     0.62501]
 [0.5     0.5     0.5    ]]


##### (Automatically):

In [1243]:
expectation = get_expectation(nr_persons=4,nr_tickets=3)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(4,3))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None None]
 [p21 p22 None]
 [p31 p32 p33]
 [p41 p42 p43]]
p11: 0.525848
p21: 0.5
p31: 0.5
p41: 0.5
p22: 0.554691
p32: 0.5
p42: 0.5
p33: 0.625006
p43: 0.5

 == Corresponding to: == 
[[0.52585 0.      0.     ]
 [0.5     0.55469 0.     ]
 [0.5     0.5     0.62501]
 [0.5     0.5     0.5    ]]


# 2 tickets - 5 persons
##### (Automatically):


In [1244]:
p11, p21, p31, p41, p51 = sp.symbols('p11, p21, p31, p41, p51')
p22, p32, p42, p52      = sp.symbols('p22, p32, p42, p52')

vars = [p11, p21, p31, p41, p51, p22, p32, p42, p52]

expectation = get_expectation(nr_persons=5,nr_tickets=2)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(5,2))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None]
 [p21 p22]
 [p31 p32]
 [p41 p42]
 [p51 p52]]
p11: 0.651129
p21: 0.607422
p31: 0.554688
p41: 0.5
p51: 0.5
p22: 0.741737
p32: 0.695311
p42: 0.625002
p52: 0.5

 == Corresponding to: == 
[[0.65113 0.     ]
 [0.60742 0.74174]
 [0.55469 0.69531]
 [0.5     0.625  ]
 [0.5     0.5    ]]


# 3 tickets - 5 persons:
##### (Automatically):

In [1245]:
## Creating sympy variable ##
person_indexes = [i+1 for i in range(5)]
vars_string = ""
for ticket in range(3):
    for person in range(5):
        if ticket <= person:
            vars_string += "p"+str(person+1)+str(ticket+1)+", "
vars_string = vars_string[:-2]
vars = sp.symbols(vars_string)

expectation = get_expectation(nr_persons=5,nr_tickets=3)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(5,3))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None None]
 [p21 p22 None]
 [p31 p32 p33]
 [p41 p42 p43]
 [p51 p52 p53]]
p11: 0.5612
p21: 0.525849
p31: 0.5
p41: 0.5
p51: 0.5
p22: 0.60742
p32: 0.554688
p42: 0.5
p52: 0.5
p33: 0.69532
p43: 0.624999
p53: 0.5

 == Corresponding to: == 
[[0.5612  0.      0.     ]
 [0.52585 0.60742 0.     ]
 [0.5     0.55469 0.69532]
 [0.5     0.5     0.625  ]
 [0.5     0.5     0.5    ]]


# Testing higher numbers
##### (Automatically):

In [1246]:
nr_persons = 10
nr_tickets = 5

person_indexes = [i+1 for i in range(nr_persons)]
vars_string = ""
for ticket in range(nr_tickets):
    for person in range(nr_persons):
        if ticket <= person:
            vars_string += "p"+str(person+1)+str(ticket+1)+", "
vars_string = vars_string[:-2]
vars = sp.symbols(vars_string)

expectation = get_expectation(nr_persons=nr_persons,nr_tickets=nr_tickets)
equations = [sp.diff(expectation, var) for var in vars]
initial_guess = [0.5 for i in range(len(vars))]
_ = optimize_equations(vars, equations, initial_guess)

table = np.zeros(shape=(nr_persons,nr_tickets))
for idx, var in enumerate(vars):
    col, row = int(str(var)[-1])-1, int(str(var)[-2])-1
    table[row][col] = np.round(_[idx],5)
print("\n == Corresponding to: == ")
print(table)

[[p11 None None None None]
 [p21 p22 None None None]
 [p31 p32 p33 None None]
 [p41 p42 p43 p44 None]
 [p51 p52 p53 p54 p55]
 [p61 p62 p63 p64 p65]
 [p71 p72 p73 p74 p75]
 [p81 p82 p83 p84 p85]
 [p91 p92 p93 p94 p95]
 [p101 p102 p103 p104 p105]]
p11: 0.583094
p21: 0.560907
p31: 0.539226
p41: 0.52009
p51: 0.506271
p61: 0.5
p71: 0.5
p81: 0.5
p91: 0.5
p101: 0.5
p22: 0.61474
p32: 0.588953
p42: 0.561811
p52: 0.535101
p62: 0.512603
p72: 0.5
p82: 0.5
p92: 0.5
p102: 0.5
p33: 0.657396
p43: 0.628893
p53: 0.596618
p63: 0.561198
p73: 0.525848
p83: 0.5
p93: 0.5
p103: 0.5
p44: 0.716168
p54: 0.68674
p64: 0.651112
p74: 0.607421
p84: 0.554687
p94: 0.5
p104: 0.5
p55: 0.801053
p65: 0.775145
p75: 0.741784
p85: 0.695295
p95: 0.625002
p105: 0.5

 == Corresponding to: == 
[[0.58309 0.      0.      0.      0.     ]
 [0.56091 0.61474 0.      0.      0.     ]
 [0.53923 0.58895 0.6574  0.      0.     ]
 [0.52009 0.56181 0.62889 0.71617 0.     ]
 [0.50627 0.5351  0.59662 0.68674 0.80105]
 [0.5     0.5126  0.5612 